name: Merge images to manifest

on:
  workflow_call:
    inputs:
      runner-os:
        description: Operating system ("ubuntu-22.04")
        type: string
        required: true

jobs:
  merge:
    name: Merge Image
    runs-on: ${{ inputs.runner-os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Image name
        id: image_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ghcr.io/${{ github.repository }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create Manifest (runtime)
        uses: ./.github/actions/create-manifest-for-target
        with:
          name: ${{ steps.image_name.outputs.lowercase }}
          target: runtime
      - name: Create Manifest (builder)
        uses: ./.github/actions/create-manifest-for-target
        with:
          name: ${{ steps.image_name.outputs.lowercase }}
          target: builder
      - name: Create Manifest (builder_nodejs)
        uses: ./.github/actions/create-manifest-for-target
        with:
          name: ${{ steps.image_name.outputs.lowercase }}
          target: builder_nodejs
      - name: Create Manifest (vscode)
        uses: ./.github/actions/create-manifest-for-target
        with:
          name: ${{ steps.image_name.outputs.lowercase }}
          target: vscode
