name: Pull Requests

on:
  pull_request:

permissions:
  actions: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        platform: ['linux/amd64', 'linux/arm64']
        os: ['ubuntu-22.04']
    with:
      runner-os: ${{ matrix.os }}
      platform: ${{ matrix.platform }}
      cache-key: ${{ matrix.os }}-buildx-${{ matrix.platform }}-pr-${{ github.event.number }}-${{ github.sha }}
      cache-restore-keys: |
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-pr-${{ github.event.number }}-
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-pr-
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-main-
